### ISSUE TITLE
老哥，能来个安装跟操作手册不

### ISSUE THREAD

**Issue by epony4c** [CTF-MissFeng/bayonet#1]
XD

**Comment by CTF-MissFeng** [comment]
已更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Explo1t"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月20日(星期四) 晚上10:57
收件人:&nbsp;"CTF-MissFeng/bayonet"<bayonet@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[CTF-MissFeng/bayonet] 老哥，能来个安装跟操作手册不 (#1)




XD

**Comment by epony4c** [comment]
感谢~
