### ISSUE TITLE
新版本添加了些什么变化呢？？

### ISSUE THREAD

**Issue by coffeehb** [CTF-MissFeng/bayonet#10]
新版本有些什么变化呢？？

**Comment by CTF-MissFeng** [comment]
> 新版本有些什么变化呢？？

首页上写的有呢

**Comment by coffeehb** [comment]
> > 新版本有些什么变化呢？？
> 
> 首页上写的有呢

抱歉，眼瞎了。。折腾一天终于跑起来了。目前一切正常。期待新功能～
