### ISSUE TITLE
是否有统一的proxy管理或设置

### ISSUE THREAD

**Issue by Mr-xn** [CTF-MissFeng/bayonet#2]
开源聚合大卡车啊！已经推荐到到我的[项目](https://github.com/Mr-xn/Penetration_Testing_POC)！  
**感谢开发，感谢开源！**   
开发不易，还没有阅读源码的，想问一下是不是有统一的proxy/proxy池支持、设置或管理，还是需要单独去每个工具里面设置,或者是在主机上设置所有的出口流量.因为现在遍地WAF...估计没怎么扫描IP就挂了.

**Comment by CTF-MissFeng** [comment]
代理池需要去各个工具模块设置，因为不是所有工具都需要代理哦。
