### ISSUE TITLE
windows下运行chrome爬虫模块从数据库中取不到数据

### ISSUE THREAD

**Issue by yuexia-wuyimin** [CTF-MissFeng/bayonet#21]
![image](https://user-images.githubusercontent.com/6943339/75997993-1e0b7d00-5f3b-11ea-9a00-60528f6f4148.png)
单独运行run_chromium.py ，取url进行爬虫的时候这里一直返回none.数据库中是有数据的
环境：
window10，python3.7.

**Comment by CTF-MissFeng** [comment]
> ![图片](https://user-images.githubusercontent.com/6943339/75997993-1e0b7d00-5f3b-11ea-9a00-60528f6f4148.png)
> 单独运行run_chromium.py，取URL进行爬虫的时候在这里一直返回none。数据库中是有数据的
> 环境：
> window10，python3.7。

这里是数据库定义模型，不是实际运行的，你有什么问题吗？

**Comment by yuexia-wuyimin** [comment]
问题解决了，谢谢大佬
