### ISSUE TITLE
关于使用的疑问？

### ISSUE THREAD

**Issue by starnightcyber** [CTF-MissFeng/bayonet#23]
您好，我使用docker的方式搭建起来环境，添加域名扫描。
添加之后，过一会可以看到域名的扫描结果，但是端口和漏洞数据没有。
请问，添加任务之后是会进行自动的端口 & 漏洞扫描吗？
个人感觉端口数据应该是可以出来的。

另外，是否能给个任务进度提示，我也不知道是不是任务没有跑完？反正等了蛮久的

**Comment by CTF-MissFeng** [comment]
> 您好，我使用docker的方式搭建起来环境，添加域名扫描。
> 添加之后，过一会可以看到域名的扫描结果，但是端口和漏洞数据没有。
> 请问，添加任务之后是会进行自动的端口 & 漏洞扫描吗？
> 个人感觉端口数据应该是可以出来的。
> 
> 另外，是否能给个任务进度提示，我也不知道是不是任务没有跑完？反正等了蛮久的

请查看日志记录，在web/utils/logs

**Comment by starnightcyber** [comment]
好的，日志文件路径：```/root/bayonet/web/utils/logs/bayonet.log```
日志显示如下，就没有进一步的动作了：
```
[INFOR] subdomain(79):MainThread(139735659655296) | oneforall.run:206 - 结束运行OneForAll
````

**Comment by CTF-MissFeng** [comment]
> 好的，日志文件路径：`/root/bayonet/web/utils/logs/bayonet.log`
> 日志显示如下，就没有进一步的动作了：
> 
> ```
> [INFOR] subdomain(79):MainThread(139735659655296) | oneforall.run:206 - 结束运行OneForAll
> ```

那就在nohub时分别输出各个模块的日志进行查看。另外已更新，docker里的源码为旧版，请替换进去

**Comment by 779789571** [comment]
> > 好的，日志文件路径：`/root/bayonet/web/utils/logs/bayonet.log`
> > 日志显示如下，就没有进一步的动作了：
> > ```
> > [INFOR] subdomain(79):MainThread(139735659655296) | oneforall.run:206 - 结束运行OneForAll
> > ```
> 
> 那就在nohub时分别输出各个模块的日志进行查看。另外已更新，docker里的源码为旧版，请替换进去
config.py 文件内的PortScan类下，需要添加shodan_api的key，我添加进去就会开始执行了。
