### ISSUE TITLE
docker中更新最新版本跑不起来

### ISSUE THREAD

**Issue by zongdeiqianxing** [CTF-MissFeng/bayonet#28]
更新了最新的v1.2的代码包，按照README中在docker中运行会遇到些问题

第一步会遇到文件头没有加utf8的报错，需要自己添加文件头 ，这儿反馈下
![image](https://user-images.githubusercontent.com/34082644/76726690-e4cddb00-678c-11ea-8542-1431b4c31581.png)

后面我在config文件里shodan_api 和shodan_api_key里都添加了值但是还是会报错， 
![image](https://user-images.githubusercontent.com/34082644/76727041-dd5b0180-678d-11ea-8a93-61e66ba46260.png)
![image](https://user-images.githubusercontent.com/34082644/76727045-e055f200-678d-11ea-9473-9bde9a7b3f6b.png)

**Comment by CTF-MissFeng** [comment]
> 更新了最新的v1.2的代码包，按照README中在docker中运行会遇到些问题
> 
> 初步会遇到文件头没有加utf8的报错，需要自己添加文件头，这儿反馈下
> ![图片](https://user-images.githubusercontent.com/34082644/76726690-e4cddb00-678c-11ea-8542-1431b4c31581.png)
> 
> 后面我在config文件里shodan_api和shodan_api_key里都添加了值但是还是会报错，
> ![图片](https://user-images.githubusercontent.com/34082644/76727041-dd5b0180-678d-11ea-8a93-61e66ba46260.png)
> ![图片](https://user-images.githubusercontent.com/34082644/76727045-e055f200-678d-11ea-9473-9bde9a7b3f6b.png)



> 更新了最新的v1.2的代码包，按照README中在docker中运行会遇到些问题
> 
> 初步会遇到文件头没有加utf8的报错，需要自己添加文件头，这儿反馈下
> ![图片](https://user-images.githubusercontent.com/34082644/76726690-e4cddb00-678c-11ea-8542-1431b4c31581.png)
> 
> 后面我在config文件里shodan_api和shodan_api_key里都添加了值但是还是会报错，
> ![图片](https://user-images.githubusercontent.com/34082644/76727041-dd5b0180-678d-11ea-8a93-61e66ba46260.png)
> ![图片](https://user-images.githubusercontent.com/34082644/76727045-e055f200-678d-11ea-9473-9bde9a7b3f6b.png)

docker里有python和python3命令，而bayonet.sh脚本里是python命令，需要修改为python3来执行。

**Comment by CTF-MissFeng** [comment]
> 更新了最新的v1.2的代码包，按照README中在docker中运行会遇到些问题
> 
> 初步会遇到文件头没有加utf8的报错，需要自己添加文件头，这儿反馈下
> ![图片](https://user-images.githubusercontent.com/34082644/76726690-e4cddb00-678c-11ea-8542-1431b4c31581.png)
> 
> 后面我在config文件里shodan_api和shodan_api_key里都添加了值但是还是会报错，
> ![图片](https://user-images.githubusercontent.com/34082644/76727041-dd5b0180-678d-11ea-8a93-61e66ba46260.png)
> ![图片](https://user-images.githubusercontent.com/34082644/76727045-e055f200-678d-11ea-9473-9bde9a7b3f6b.png)

已更新docker，请下载使用

**Comment by zongdeiqianxing** [comment]
谢谢 我之前改成python3后可以跑起来了！  非常赞！
