### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by BrathonBai** [CTF-MissFeng/bayonet#31]
![image](https://user-images.githubusercontent.com/28860736/76819359-e35eea00-6842-11ea-9e78-ddba980b7fbe.png)
报错如图所示

**Comment by BrathonBai** [comment]
> ![image](https://user-images.githubusercontent.com/28860736/76819359-e35eea00-6842-11ea-9e78-ddba980b7fbe.png)
> 报错如图所示

**Comment by 0ks3iio** [comment]
没有logs文件夹，新建一个文件夹就行了
