### ISSUE TITLE
端口入库SQL错误

### ISSUE THREAD

**Issue by fuzzing0day** [CTF-MissFeng/bayonet#36]
17:18:40,606 [ALERT] Run:63 - 端口入库SQL错误:(psycopg2.errors.ForeignKeyViolation) insert or update on table "src_ports" violates foreign key constraint "src_ports_subdomain_fkey"
DETAIL:  Key (subdomain)=(xxx.com) is not present in table "src_subdomain".

[SQL: INSERT INTO src_ports (subdomain_ip, subdomain, port, service, product, version, flag, brute, port_time) VALUES (%(subdomain_ip)s, %(subdomain)s, %(port)s, %(service)s, %(product)s, %(version)s, %(flag)s, %(brute)s, %(port_time)s) RETURNING src_ports.id]
[parameters: {'subdomain_ip': '110.110.110.110', 'subdomain': 'xxx.com', 'port': 80, 'service': 'http', 'product': '', 'version': '', 'flag': False, 'brute': False, 'port_time': '2020-03-24 17:18:40'}]
(Background on this error at: http://sqlalche.me/e/gkpj)
Traceback (most recent call last):
  File "run_portscan.py", line 4, in <module>
    tools.portscan.Run.port_main()
  File "/root/bayonet/tools/portscan/Run.py", line 91, in port_main
    WriteSubDomain(results)
  File "/root/bayonet/tools/portscan/Run.py", line 40, in WriteSubDomain
    sql_subdomain = SrcSubDomain.query.filter(SrcSubDomain.subdomain_ip == results.subdomain_ip).all()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 705, in get
    value = state._load_expired(state, passive)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 660, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 987, in load_scalar_attributes
    raise orm_exc.ObjectDeletedError(state)
sqlalchemy.orm.exc.ObjectDeletedError: Instance '<SrcSubDomain at 0x7fd6ae270370>' has been deleted, or its row is otherwise not present.

**Comment by fuzzing0day** [comment]
![image](https://user-images.githubusercontent.com/44494442/77419286-1f75ea00-6e03-11ea-87e3-5e2cab81fe86.png)

**Comment by fuzzing0day** [comment]
DETAIL: Key (subdomain)=(xxx.com) is not present in table "src_subdomain".

手工确认了，表里面是有的。

**Comment by CTF-MissFeng** [comment]
> 详细信息：表（src_subdomain）中不存在键（subdomain）=（xxx.com）。
> 
> 手工确认了，表里面是有的。

这是因为子域名表和漏洞表是关联的，但是获取漏洞时没能匹配到获取子域名表对应的子域名，可以将下面的数据库定义模型删除掉关联，就不会报错了。目前这个关联关系没用到。

将web/models.py
![image](https://user-images.githubusercontent.com/38177965/77420769-97ddaa80-6e05-11ea-9f53-078d51c90fe7.png)
![image](https://user-images.githubusercontent.com/38177965/77420808-a7f58a00-6e05-11ea-94df-3a9fef7bd10e.png)
