### ISSUE TITLE
待扫描ip数是什么意思呢？

### ISSUE THREAD

**Issue by handbye** [CTF-MissFeng/bayonet#43]
为什么添加了很久的任务还是有很多待扫描ip，有的就没扫描过
![无标题](https://user-images.githubusercontent.com/26617058/77916802-3d908e00-72cc-11ea-9e6a-2a10763e8e2e.png)

**Comment by CTF-MissFeng** [comment]
> 为什么添加了很久的任务还是有很多待扫描ip，有的就没扫描过
> ![无标题](https://user-images.githubusercontent.com/26617058/77916802-3d908e00-72cc-11ea-9e6a-2a10763e8e2e.png)

nmap和shodan跑完才算完成一个ip

**Comment by handbye** [comment]
> > 为什么添加了很久的任务还是有很多待扫描ip，有的就没扫描过
> > ![无标题](https://user-images.githubusercontent.com/26617058/77916802-3d908e00-72cc-11ea-9e6a-2a10763e8e2e.png)
> 
> nmap和shodan跑完才算完成一个ip

如果子域名已经扫完了，没扫完的ip还会继续扫描吗，任务会不会终止掉。
